openapi: 3.0.2
components:
  parameters:
    GuardIDParam:
      in: path
      name: id
      required: true
      description: Guard guard id
      schema:
        type: integer
        format: int64
  requestBodies:
    PutRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutRequest'
          examples:
            request:
              $ref: '#/components/examples/PutRequest'
  responses:
    PutResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutResult'
          examples:
            response:
              $ref: '#/components/examples/PutResult'
  schemas:
    PutRequest:
      type: object
      properties:
        phone_number:
          type: string
          description: Need to add the international area code

    PutResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                      description: User id
                    username:
                      type: string
                      description: User name
                    first_name:
                      type: string
                      description: User surname
                    last_name:
                      type: string
                      description: User name
                    lang:
                      type: string
                      description: language
                    timezone:
                      type: string
                      description: The time zone
                    activated:
                      type: boolean
                      enum:
                        - true
                        - false
                    role:
                      type: string
                      description: User role
                phone_number:
                  type: string
                  description: Need to add the international area code

  examples:
    PutRequest:
      value:
        phone_number: 13111112234

    PutResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          user:
            id: 18
            username: guard@turingvideo.net
            last_name: ""
            first_name: ""
            lang: en
            timezone: America/Los_Angeles
            activated: false
            role: guard
          phone_number: 13111113334
