openapi: 3.0.2
components:
  parameters:
    GuardCaseIDParam:
      in: path
      name: id
      required: true
      description: Guard case id
      schema:
        type: integer
        format: int32
  requestBodies:
    UpdateRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateRequest'
          examples:
            request:
              $ref: '#/components/examples/UpdateRequest'
  responses:
    CaseListResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaseListResult'
          examples:
            response:
              $ref: '#/components/examples/CaseListResult'
    CaseResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaseResult'
          examples:
            response:
              $ref: '#/components/examples/CaseResult'
  schemas:
    UpdateRequest:
      type: object
      required:
        - action
      properties:
        action:
          $ref: '#/components/schemas/Action'
        note:
          type: string
          description: An operator adds note to a case
    Action:
      type: string
      description: |
        Action indicates the operation performed by an operator/guard
        * `new`: Default action.
        * `viewed`: A case is viewed by an operator.
        * `false_alarm`: A case is false alarm.
        * `no_harm`: A case is not false alarm but actually safe.
        * `call_police`: A case needs to escalate to police.
        * `dispatch_guard`: A case needs to dispatch a guard.
        * `update_priority`: Update the priority of a case.
        * `dispatch_robot`: Dispatch a robot to resolve a case.
        * `accept_case`: Update the status of a case.
        * `start`: A guard has started to resolve a case.
        * `arrive`: A guard has arrived.
        * `resolve_case`: A guard has resolved a case.
        * `add_note`: An operator adds note to a case.
        * `close`: An operator closes a case.
        * `update_types`: An operator updates a type.
        * `notify_customer`: An operator notifies a customer
      enum:
        - new
        - viewed
        - false_alarm
        - no_harm
        - call_police
        - dispatch_guard
        - update_priority
        - dispatch_robot
        - accept_case
        - start
        - arrive
        - resolve_case
        - add_note
        - close
        - update_types
        - notify_customer
    CaseListResult:
      description: Guard case list
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/CaseInfo'

    CaseResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/CaseInfo'

    CaseInfo:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Guard case id
        created_at:
          type: string
          format: date-time
          description: Case create time
        updated_at:
          type: string
          format: date-time
          description: Case update time
        event_id:
          type: integer
          format: int64
          description: Event id
        incident_id:
          type: integer
          format: int64
        operator_id:
          type: integer
          format: int64
        guard_id:
          type: integer
          format: int64
        report:
          type: string
        viewed:
          type: boolean
          enum:
            - true
            - false
          description: whether the case is viewed
        status:
          type: object
          properties:
            name:
              type: string
              description: |
                Status indicates the current handling stage of a case.
                * `new`: A case has just been created and waiting for handling.
                * `assigned`: A case has been assigned to a guard by an operator.
                * `accepted`: A case has been accepted by a guard.
                * `on_the_way`: A guard has started to resolve this case.
                * `arrived`: A guard has arrived on the case.
                * `resolved`: A case has been resolved by a guard.
                * `notified`: A case has been sent to notification.
                * `closed`: A case has been closed by an operator.
              enum:
                - new
                - assigned
                - accepted
                - on_the_Way
                - arrived
                - resolved
                - notified
                - closed
            label:
              type: string
              enum:
                - New
                - Assigned
                - Accepted
                - On the Way
                - Arrived
                - Resolved
                - Notified
                - Closed
        mediums:
          type: array
          items:
            type: string
        priority:
          type: object
          properties:
            name:
              type: string
              enum:
                - low
                - medium
                - high
                - unassigned
            label:
              type: string
              enum:
                - Low
                - Medium
                - High
                - Unassigned
        robot_id:
          type: string
        event:
          allOf:
            - $ref: '../event/eventEvents.yaml#/components/schemas/EventInfo'
            - type: object
              properties:
                closed_at:
                  type: string
                  format: date-time
                  description: Event closed time
        incident:
          type: string
        notes:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: Guard note id
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              user_id:
                type: integer
                format: int32
              note:
                type: string
                description: Case note
        histories:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: Guard histoy case id
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              user_id:
                type: integer
                format: int32
              action:
                $ref: '#/components/schemas/Action'
        inspection_id:
          type: integer
          format: int64
          description: Inspection materials id
        inspection:
          type: string
          description: Inspection materials info
        action:
          $ref: '#/components/schemas/Action'

  examples:
    UpdateRequest:
      value:
        action: add_note
        note: this is test
    CaseListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: http://test.turingvideo.cn:8000/api/v1/new_case/cases?limit=10&offset=10
          previous: null
          results:
            - id: 154
              created_at: '2019-10-22T09:37:45Z'
              updated_at: '2019-10-22T09:37:45Z'
              event_id: 103
              incident_id: null
              operator_id: null
              guard_id: null
              report: null
              viewed: false
              status:
                name: new
                label: New
              mediums:
                -
              priority:
                name: unassigned
                label: Unassigned
              robot_id: null
              event:
                id: 103
                camera_id: 3
                robot_id: null
                robot_camera:
                  name: front
                  lablel: Front camera
                camera:
                  id: 3
                  name: AQ仓库
                robot: null
                types:
                  - name: person:513
                    label: person:513
                started_at: '2017-10-18T06:00:57Z'
                ended_at: '2017-10-19T06:01:57Z'
                mediums:
                  - id: 143
                    name: snapshot
                    file:
                      file_size: 8888
                      size:
                        - 640
                        - 360
                      content_type: image/jpeg
                      url: https://dev-turingvideo-com.s3.cn/users/3/cameras/3/events/8d40608
                    event_id: 103
                  - id: 144
                    name: bbox
                    file:
                      file_size: 8888
                      content_type: text/json
                      url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                    event_id: 103
                  - id: 145
                    name: video
                    file:
                      file_size: 8888
                      content_type: video/mp4
                      url: https://develop-data-turingvideo-com
                    event_id: 103
                robot_data: null
                camera_data:
                  threshold: 0.5
                media:
                  snapshot:
                    id: 143
                    name: snapshot
                    file:
                      file_size: 8888
                      size:
                        - 640
                        - 360
                      content_type: image/jpeg
                      url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                    event_id: 103
                  bbox:
                    id: 144
                    name: bbox
                    file:
                      file_size: 8888
                      content_type: text/json
                      url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                    event_id: 103
                  videos:
                    - id: 145
                      name: video
                      file:
                        file_size: 8888
                        content_type: video/mp4
                        url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                      event_id: 103
                      started_at: '2017-10-18T06:00:57Z'
                      ended_at: '2017-10-19T06:00:57Z'
                location:
                  lat: 0.0
                  lng: 0.0
                metadata: {}
                source: camera
                tag: ""
                marked: false
                viewed: false
                annotate: unknown
                site:
                  id: 1
                  created_at: '2019-08-16T09:06:45Z'
                  updated_at: '2019-08-16T09:15:22Z'
                  name: test-site
                  location: Nanjing/China
                  note: ''
                  label: Zidong
                  county: 栖霞区
                  province: 江苏省
                  city: 南京市
                  polygons: []
                closed_at: '2019-10-22T09:37:45.756376Z'
              incident: null
              notes:
                - id: 4
                  created_at: '2020-04-08T03:35:24Z'
                  updated_at: '2020-04-08T03:35:24Z'
                  user_id: 1
                  note: this is test
              histories:
                - id: 3
                  created_at: '2020-04-08T02:13:21Z'
                  updated_at: '2020-04-08T02:13:21Z'
                  user_id: 1
                  action:
                    name: add_note
                    label: Add Note
              inspection_id: null
              inspection: null
              action: new

    CaseResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 154
          created_at: '2019-10-22T09:37:45Z'
          updated_at: '2019-10-22T09:37:45Z'
          event_id: 103
          incident_id: null
          operator_id: null
          guard_id: null
          report: null
          viewed: false
          status:
            name: new
            label: New
          mediums:
            -
          priority:
            name: unassigned
            label: Unassigned
          robot_id: null
          event:
            id: 103
            camera_id: 3
            robot_id: null
            robot_camera:
              name: front
              lablel: Front camera
            camera:
              id: 3
              name: AQ仓库
            robot: null
            types:
              - name: person:513
                label: person:513
            started_at: '2017-10-18T06:00:57Z'
            ended_at: '2017-10-19T06:01:57Z'
            mediums:
              - id: 143
                name: snapshot
                file:
                  file_size: 8888
                  size:
                    - 640
                    - 360
                  content_type: image/jpeg
                  url: https://dev-turingvideo-com.s3.cn/users/3/cameras/3/events/8d40608
                event_id: 103
              - id: 144
                name: bbox
                file:
                  file_size: 8888
                  content_type: text/json
                  url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                event_id: 103
              - id: 145
                name: video
                file:
                  file_size: 8888
                  content_type: video/mp4
                  url: https://develop-data-turingvideo-com
                event_id: 103
            robot_data: null
            camera_data:
              threshold: 0.5
            media:
              snapshot:
                id: 143
                name: snapshot
                file:
                  file_size: 8888
                  size:
                    - 640
                    - 360
                  content_type: image/jpeg
                  url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                event_id: 103
              bbox:
                id: 144
                name: bbox
                file:
                  file_size: 8888
                  content_type: text/json
                  url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                event_id: 103
              videos:
                - id: 145
                  name: video
                  file:
                    file_size: 8888
                    content_type: video/mp4
                    url: https://deveamazonaws.com.cn/users/3/cameras/3/events/0dc84d2ab17b30
                  event_id: 103
                  started_at: '2017-10-18T06:00:57Z'
                  ended_at: '2017-10-19T06:00:57Z'
            location:
              lat: 0.0
              lng: 0.0
            metadata: {}
            source: camera
            tag: ""
            marked: false
            viewed: false
            annotate: unknown
            site:
              id: 1
              created_at: '2019-08-16T09:06:45Z'
              updated_at: '2019-08-16T09:15:22Z'
              name: test-site
              location: Nanjing/China
              note: ''
              label: Zidong
              county: 栖霞区
              province: 江苏省
              city: 南京市
              polygons: []
            closed_at: '2019-10-22T09:37:45.756376Z'
          incident: null
          notes:
            - id: 4
              created_at: '2020-04-08T03:35:24Z'
              updated_at: '2020-04-08T03:35:24Z'
              user_id: 1
              note: this is test
          histories:
            - id: 3
              created_at: '2020-04-08T02:13:21Z'
              updated_at: '2020-04-08T02:13:21Z'
              user_id: 1
              action:
                name: add_note
                label: Add Note
          inspection_id: null
          inspection: null
          action: new