db_version: default

api_case:
  auth_change_password: default
  auth_login: default
  auth_register_android_device: default
  auth_register_IOS_device: default
  auth_reset_password: default
  box_authenticate_box: default
  box_box_create_camera: default
  box_box_create_video: default
  box_box_debug_login: default
  box_box_delete_camera: default
  box_box_get_differences: default
  box_box_get_meta: default
  box_box_saving_video: default
  box_box_update_camera: default
  box_camera_auto_update: default
  box_camera_get_differences: default
  box_camera_list: default
  box_claim_box: default
#  box_create_camera_video: default
  box_create_snap: default
  box_get_config: default
  box_get_stream_token: default
  box_get_token: default
  box_initiate_box: default
  box_list_box: default
  box_list_camera_video: default
  box_list_camera_video_another: default
  box_retrieve_box: default
  box_retrieve_camera: default
  box_save_camera_video: default
  box_slot_camera_video: default
  box_snap_slot: default
  box_unclaim_box: default
  box_update_box: default
  box_update_state: default
  box_user_create_camera: default
  box_user_delete_camera: default
  box_user_update_camera: default
  public_all_event_types: default
  public_create_box_event: default
  public_create_robot_event: default
  public_delete_event: default
  public_event_slot: default
  public_get_agent_meta: default
  public_get_global_config: default
  public_get_timezones: default
  public_list_all_event: default
  public_list_event: default
  public_list_inspection: default
  public_inspection_history: default
  public_me: default
  public_monitor: default
  public_retrieve_an_event: default
  public_retrieve_inspection: default
  robot_create_patrol: default
  robot_create_robot_video: default
  robot_create_route: default
  robot_get_analytics_token: default
  robot_get_config: default
  robot_get_stream_token: default
  robot_get_token: default
  robot_list_robot: default
  robot_list_robot_video: default
  robot_retrieve_robot: default
  robot_retrieve_route: default
  robot_robot_authenticate: default
  robot_robot_debug_login: default
  robot_robot_get_differences: default
  robot_robot_get_meta: default
  robot_robot_initiate: default
  robot_robot_save_video: default
  robot_robot_video_slot: default
  robot_unclaim_robot: default
  robot_update_robot: default
  robot_update_robot_meta: default
  robot_update_state: default
  robot_create_robot_snap: default
  robot_get_robot_snap_slot: default
#  public_batch_update_event: default
  robot_claim_robot: default
  # perm
  perm_validate_resource_scope: default
  perm_validate_cross_join: default
  perm_get_queryset_sql: default
  perm_check_conditions: default
  #  org
  manage_domain_types_list: default
  manage_create_domain_type: default
  manage_retrieve_an_domain_type: default
  manage_update_domain_type: default
  manage_delete_domain_type: default
  manage_domain_list: default
  manage_retrieve_an_domain: default
  manage_create_domain: default
  manage_update_domain: default
  manage_delete_domain: default
  manage_create_domain_user: default
  manage_user_nodes_list: default
  manage_retrieve_an_user_node: default
  manage_create_user_roles: default
  manage_edit_user_roles: default
  manage_change_parent: default
  manage_remove_user: default
  # guard
  guard_create_guard: default
  guard_create_guard_admin: default
  guard_create_guard_company: default
  guard_create_monitoring_operator: default
  guard_delete_guard_admin: default
  guard_guard_list: default
  guard_guard_admin_list: default
  guard_guard_company_list: default
  guard_monitoring_operator_list: default
  guard_retrieve_an_guard: default
  guard_retrieve_an_guard_admin: default
  guard_retrieve_an_guard_company: default
  guard_retrieve_an_monitoring_operator: default
  guard_update_guard: default
  guard_update_guard_admin: default
  guard_update_guard_company: default
#  guard_update_monitoring_operator: default   # Cannot log in with correct user password
  guard_list_cases: default
  guard_update_cases: default
  manage_validate_get_organization: default
  # map
  map_create_map_config: default
  map_map_config_list: default
  map_retrieve_an_map_config: default
  map_delete_map_config: default
  map_create_map_maps: default
  map_maps_list: default
  map_retrieve_an_map_maps: default
  map_delete_map_maps: default
  map_maps_add_target: default
  map_maps_remove_target: default
  map_site_add_map: default
  map_site_remove_map: default
  map_domain_set_map: default
  map_domain_unset_map: default
  map_create_target: default
  map_targets_list: default
  map_retrieve_an_target: default
  map_delete_target: default
  map_site_manager_user_test: default
# iot
  iot_retrieve_agent_box: default
  iot_retrieve_agent_robot: default
  iot_device_get_associated_device: default
  iot_device_min_latest: default
