# Name: test_default.tavern
test_name: Box Get Meta
stages:
  - type: ref
    id: login_customer
  - name: Box Get Meta
    request:
      url: "{url}/box/boxes/{test_box_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 200
      body:
        ret:
          id: "{test_box_id}"
          agent: !anything
          algos: !anything
          max_detect_cnt: !anyint
          max_camera_cnt: !anyint
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
 #   delay_after: 1

---
test_name: Box error to get meta
marks:
  - parametrize:
      key: err_box_id
      vals:
        - 12312
        - qweasd
stages:
  - type: ref
    id: login_customer
  - name: Box error to get meta
    request:
      url: "{url}/box/boxes/{err_box_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 409
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_409
 #   delay_after: 1
---
test_name: Box error to get meta
marks:
  - parametrize:
      key: err_box_id
      vals:
        - wqe@#$%1424
stages:
  - type: ref
    id: login_customer
  - name: Box error to get meta
    request:
      url: "{url}/box/boxes/{err_box_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 404
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_404
 ##   delay_after: 1