# Name: test_default.tavern
test_name: Retrieve an guard_admin
stages:
  - type: ref
    id: login_guard_admin
  - name: Retrieve an guard_admin
    request:
      url: "{url}/guard_admin/guard_admins/4"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        err: !anything
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
