# Name: test_default.tavern
test_name: View the robot list info
stages:
  - type: ref
    id: login_customer
  - name: View the robot list info
    request:
      url: "{url}/robot/robots"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        ret: !anything
        $ext:
          function: api_tests.utils.validation_method:validate_err_200

---
test_name: method error to view the robot list info
stages:
  - type: ref
    id: login_customer
  - name: method error
    request:
      url: "{url}/robot/robots"
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 403
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_403

---
test_name: Not logged in to see robot list information
stages:
  - name: Not logged in to see robot list information
    request:
      url: "{url}/robot/robots"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 401
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_401