openapi: 3.0.2

components:
  parameters:
    OrgIDParam:
      in: path
      name: id
      required: true
      description: Org id
      schema:
        type: integer
        format: int32
  requestBodies:
    OrgRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrgRequest'

  responses:
    OrgListResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrgListResult'
          examples:
            response:
              $ref: '#/components/examples/OrgListResult'
    OrgResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrgResult'
          examples:
            response:
              $ref: '#/components/examples/OrgResult'
  schemas:
    OrgRequest:
      type: object
      properties:
        events_expire:
          type: integer
          format: int32
          description: Events expire time
        videos_expire:
          type: integer
          format: int32
          description: Videos expire time
        snaps_expire:
          type: integer
          format: int32
          description: Snaps expire time
        saved_videos_expire:
          type: integer
          format: int32
          description: Saved_videos expire time
        robot_assets_expire:
          type: integer
          format: int32
          description: Robot_assets expire time
        analytics_robot_logs_expire:
          type: integer
          format: int32
          description: Analytics_robot_logs expire time
        analytics_robot_lidar_expire:
          type: integer
          format: int32
          description: Analytics_robot_lidar expire time
        camera_preview_expire:
          type: integer
          format: int32
          description: Camera_preview expire time
        camera_samples_expire:
          type: integer
          format: int32
          description: Camera_samples expire time
    OrgListResult:
      description: Get information about all organizations
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/OrgInfo'
    OrgResult:
      description: Get information about an organization
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/OrgInfo'
    OrgInfo:
      type: object
      properties:
        events_expire:
          type: integer
          format: int32
          description: Events expire time
        videos_expire:
          type: integer
          format: int32
          description: Videos expire time
        snaps_expire:
          type: integer
          format: int32
          description: Snaps expire time
        saved_videos_expire:
          type: integer
          format: int32
          description: Saved_videos expire time
        robot_assets_expire:
          type: integer
          format: int32
          description: Robot_assets expire time
        analytics_robot_logs_expire:
          type: integer
          format: int32
          description: Analytics_robot_logs expire time
        analytics_robot_lidar_expire:
          type: integer
          format: int32
          description: Analytics_robot_lidar expire time
        camera_preview_expire:
          type: integer
          format: int32
          description: Camera_preview expire time
        camera_samples_expire:
          type: integer
          format: int32
          description: Camera_samples expire time
        enable_face_detection:
          type: boolean
          enum:
            - true
            - false
          description: Whether to enable face detection
        id:
          type: integer
          description: Organization id
        code_name:
          type: string
          description: Organization code_name
        name:
          type: string
          description: Organization name
        owner_id:
          type: integer
          description: User id to which the organization belongs
        event_type_mode:
          type: string
          description: Event type permissions
          enum:
            - sys_and_customized
            - customized
            - sys

  examples:
    OrgListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - events_expire: 0
              videos_expire: 0
              snaps_expire: 0
              saved_videos_expire: 0
              robot_assets_expire: 0
              analytics_robot_logs_expire: 0
              analytics_robot_lidar_expire: 0
              camera_preview_expire: 0
              camera_samples_expire: 0
              enable_face_detection: false
              id: 1
              code_name: test_org
              name: 测试
              owner_id: 2
              event_type_mode: sys_and_customized

    OrgResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          events_expire: 0
          videos_expire: 0
          snaps_expire: 0
          saved_videos_expire: 0
          robot_assets_expire: 0
          analytics_robot_logs_expire: 0
          analytics_robot_lidar_expire: 0
          camera_preview_expire: 0
          camera_samples_expire: 0
          enable_face_detection: false
          id: 1
          code_name: test_org
          name: 测试
          owner_id: 2
          event_type_mode: sys_and_customized
