# Name: test_default.tavern
test_name: Create domain parent (org)
stages:
  - type: ref
    id: login_customer
  - name: Create domain
    request: &type_request_anchor
      url: "{url}/domain/domains"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        name: "parent"
        code_name: "domain_test_parent"
        domain_type_id:  1
        parent_id: null
    response:
      status_code: 200
      body:
        ret:
          id: !anyint
      save:
        $ext:
          function: api_tests.utils.validation_method:validate_get_domain_parent_id
---
test_name: Create domain child (org)
stages:
  - type: ref
    id: login_customer
  - name: Create domain
    request:
      <<: *type_request_anchor
      json:
        name: "child"
        code_name: "domain_test_child"
        domain_type_id: 2
        parent_id: "{domain_parent_id}"
    response:
      status_code: 200
      body:
        ret:
          id: !anyint
        $ext:
          function: api_tests.utils.validation_method:validate_err_200

---
test_name: Repeat create domain (org)
stages:
  - type: ref
    id: login_customer
  - name: Repeat create domain
    request:
      <<: *type_request_anchor
      json:
        name: "child"
        code_name: "domain_test_child"
        domain_type_id: 2
        parent_id: "{domain_parent_id}"
    response:
      status_code: 409
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_409
