# Name: test_default.tavern
test_name: Delete map (customer)
stages:
  - type: ref
    id: login_customer
  - name: Create map
    request:
      url: "{url}/map/maps"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        map_config_id: 1
        center_point:
          lat: 32.0571355
          lng: 118.77807341
        initial_zoom: 8
        min_zoom: 2
        max_zoom: 6
        data:
          tavern: test
    response:
      status_code: 200
      body:
        ret:
          id: !anyint
      save:
        body:
          del_id: ret.id
  - name: Delete map
    request:
      url: "{url}/map/maps/{del_id}"
      method: DELETE
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
    response:
      status_code: 200
      body:
        ret:
          id: !int "{del_id}"
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
