# Name: test_default.tavern
test_name: Create Robot Snap
stages:
  - type: ref
    id: login_customer
  - type: ref
    id: robot_initiate
  - type: ref
    id: robot_authenticate
  - name: Create Robot Snap
    request:
      url: "{url}/robot_snap/robot_snaps"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
        Referer: "{Referer}"
      json:
        camera: "{robot_camera_name}"
        type: event
        timestamp: '2019-09-26T06:27:57.262076Z'
        file:
          Key: users/1/cameras/1/events/logo.jpg
          Bucket: develop-data-turingvideo-com
          meta:
            file_size: 1888
            content_type: image/jpeg
    response:
      status_code: 200
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
 #   delay_after: 1

---
test_name: Create Snap error(Box)
marks:
  - parametrize:
      key:
        - err_camera_id
        - err_type
        - err_timestamp
        - err_Key
        - err_Bucket
        - err_file_size
        - err_size1
        - err_size2
        - err_content_type
      vals:
        - ["", "", "", "", "", "", "", "", ""]
        - ["{robot_camera_name}", "", "2019-09-26T06:17:57.262076Z", "users/1/ts/logo.jpg", "develop-data-turingvideo-com", "1888", "640", "360", "image/jpeg"]
        - ["{robot_camera_name}", event, "", "users/1/ts/logo.jpg", "develop-data-turingvideo-com", "1888", "640", "360", "image/jpeg"]
        - ["{robot_camera_name}", event, "2019-09-26T06:17:57.262076Z", "", "develop-data-turingvideo-com", "1888", "640", "360", "image/jpeg"]
        - ["{robot_camera_name}", event, "2019-09-26T06:17:57.262076Z", "users/1/ts/logo.jpg", "", "1888", "640", "360", "image/jpeg"]
        - ["{robot_camera_name}", event, "2019-09-26T06:17:57.262076Z", "users/1/ts/logo.jpg", "develop-data-turingvideo-com", "", "640", "360", "image/jpeg"]
        - ["{robot_camera_name}", event, "2019-09-26T06:17:57.262076Z", "users/1/ts/logo.jpg", "develop-data-turingvideo-com", "1888", "640", "360", ""]

stages:
  - type: ref
    id: login_customer
  - type: ref
    id: robot_initiate
  - type: ref
    id: robot_authenticate
  - name: Create Snap error(Box)
    request:
      url: "{url}/robot_snap/robot_snaps"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
        Referer: "{Referer}"
      json:
        camera_id: "{err_camera_id}"
        type: "{err_type}"
        timestamp: "{err_timestamp}"
        file:
          Key: "{err_Key}"
          Bucket: "{err_Bucket}"
          meta:
            file_size: "{err_file_size}"
            size:
              - "{err_size1}"
              - "{err_size2}"
            content_type: "{err_content_type}"
    response:
      status_code: 400
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_400
 #   delay_after: 1