openapi: 3.0.2
components:
  responses:
    200:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Result'
          examples:
            response:
              $ref: '#/components/examples/Result'
  schemas:
    Result:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                    description: Target id
                  floor:
                    type: integer
                    format: int32
                    description: Positive and negative numbers indicate floors

  examples:
    Result:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          - id: 3
            floor: -1
          - id: 3
            floor: 2
