# Name: test_default.tavern
test_name: Get robot information
stages:
  - type: ref
    id: login_customer
  - name: Get robot information from robot_id
    request:
      url: "{url}/robot/robots/{test_robot_id}"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
 #   delay_after: 1

---
test_name: Use the wrong robot_id to query
marks:
  - parametrize:
      key: err_robot_id
      vals:
        - "aaa@@#33"
        - "robot_no_exist"
        - "99999"
stages:
  - type: ref
    id: login_customer
  - name: Use the wrong camera id to query
    request:
      url: "{url}/robot/robots/{err_robot_id}"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 404
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_404
 #   delay_after: 1
