# Name: test_default.tavern
test_name: Robot get meta
stages:
  - type: ref
    id: login_customer
  - name: Robot get meta
    request:
      url: "{url}/robot/robots/{test_robot_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 200
      body:
        ret:
          id: "{test_robot_id}"
        $ext:
          function: api_tests.utils.validation_method:validate_err_200

---
test_name: Box error to get meta
marks:
  - parametrize:
      key: err_robot_id
      vals:
        - 12312
        - qweasd
stages:
  - type: ref
    id: login_customer
  - name: Box error to get meta
    request:
      url: "{url}/box/boxes/{err_robot_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 409
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_409
 #   delay_after: 1
---
test_name: Box error to get meta
marks:
  - parametrize:
      key: err_robot_id
      vals:
        - wqe@#$%1424
stages:
  - type: ref
    id: login_customer
  - name: Box error to get meta
    request:
      url: "{url}/box/boxes/{err_robot_id}/get_meta"
      method: GET
      headers:
        content-type: application/json
#        X-CSRFTOKEN: "{get_csrftoken}"
#        Referer: "{Referer}"
    response:
      status_code: 404
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_404
 #   delay_after: 1