openapi: 3.0.2

components:
  schemas:
    ChangeRequest:
      type: object
      required:
        - old_password
        - neo_password
      properties:
        old_password:
          type: string
          format: password
        neo_password:
          type: string
          format: password
