openapi: 3.0.2

components:
  schemas:
    SetRequest:
        type: object
        required:
          - email
        properties:
          email:
            type: string
            description: Email address
            format: email
