# Name: test_default.tavern
test_name: BOX debug login
stages:
  - name: The test needs debug_login to make the browser simulate BOX
    request:
      url: "{url}/box/boxes/debug_login"
      method: POST
      headers:
        content-type: application/json
      json:
        id: "{test_box_id}"
        type: "{box_type}"
        ip_address: "{box_ip_address}"
        challenge: "challenge"
    response:
      status_code: 200
      body:
        ret:
          id: "{test_box_id}"
        err: !anything
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
---
test_name: Box debug login error
marks:
  - parametrize:
      key:
        - err_logic_box_id
        - err_box_type
        - err_box_ip_address
        - err_box_challenge
      vals:
        - ["", "", "", ""]
        - ["", "{box_type}", "{box_ip_address}", challenge]
        - ["{test_box_id}", "", "{box_ip_address}", challenge]
        - ["{test_box_id}", "{box_type}", "", challenge]
        - ["{test_box_id}", "{box_type}", "{box_ip_address}", ""]
        - ["{test_box_id}", "pc_v1_err", "{box_ip_address}", challenge]
        - ["{test_box_id}", "{box_type}", "erriperr", challenge]
        - ["{test_box_id}", "我真的是测试字段@我是测试字段我只是测试字段我真是测试字段我真段段我段段我测试字段我只是测试字段我真段段我测试字段我只是测试字段我真段段我真的是测试字段#@￥%我是测试字段我只是测试字段我真的是测试字段@我是测试字段我只是测试字段我真段段我真的是测试我真的是测试字段", "{box_ip_address}", challenge]
stages:
  - name: debug_login
    request:
      url: "{url}/box/boxes/debug_login"
      method: POST
      headers:
        content-type: application/json
      json:
        id: "{err_logic_box_id}"
        type: "{err_box_type}"
        ip_address: "{err_box_ip_address}"
#        max_camera_cnt: "{max_camera_cnt}"
#        state: "{state}"
        challenge: "{err_box_challenge}"
    response:
      status_code: 400
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_400

---
test_name: User password error to login
stages:
  - name: debug_login
    request:
      url: "{url}/box/boxes/debug_login"
      method: POST
      headers:
        content-type: application/json
      json:
        id: err_id_err001
        type: "{box_type}"
        ip_address: "{box_ip_address}"
#        max_camera_cnt: "{max_camera_cnt}"
#        state: "{state}"
        challenge: "challenge"
    response:
      status_code: 409
      body:
        err:
          em: "This instance doesn't exist any more. (none)"
        $ext:
          function: api_tests.utils.validation_method:validate_err_409
