# Name: test_default.tavern
test_name: Update domain type (org put)
stages:
  - type: ref
    id: login_customer
  - name: Update domain type
    request: &type_request_anchor
      url: "{url}/domain_type/domain_types/5"
      method: PUT
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        name: "parent"
    response: &type_response_anchor
      status_code: 200
      body:
        ret:
          id: !int 5
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
---
test_name: Update domain type (org patch)
stages:
  - type: ref
    id: login_customer
  - name: Update domain type
    request:
      <<: *type_request_anchor
      method: PATCH
    response: *type_response_anchor
