openapi: 3.0.2
components:
  responses:
    200:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Result'
          examples:
            response:
              $ref: '#/components/examples/Result'
  schemas:
    Result:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: object
              properties:
                url:
                  type: string
                  description: Video stream url
                base_uri:
                  type: string
                  description: Video stream base url

  examples:
    Result:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          url: https://dev.s3.cn-northwest-1.amazonaws.com.cn/
          base_uri: rtsps://dev-stream.turingvideo.com:8554