openapi: 3.0.2
components:
  requestBodies:
    CreateCameraRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCameraRequest'
          examples:
            request:
              $ref: '#/components/examples/CreateCameraRequest'
  responses:
    CameraListResult:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CameraListResult'
          examples:
            response:
              $ref: '#/components/examples/CameraListResult'
    CreateCameraResult:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCameraResult'
          examples:
            response:
              $ref: '#/components/examples/CreateCameraResult'
  schemas:
    CreateCameraRequest:
      type: array
      description: user create camera
      items:
        type: object
        properties:
          box_id:
            type: string
            description: Box id
          name:
            type: string
            description: Camera name
          mac_address:
            type: string
            description: IP address of the camera
          notifies:
            type: string
            description: Notify the configuration
          username:
            type: string
            description: User name of the camera
          password:
            type: string
            description: Camera password
          upload_video_enabled:
            type: boolean
            description: Upload video or not
            enum:
              - true
              - false
          uri:
            type: string
            description: Camera uri video streaming
          hd_uri:
            type: string
            description: Camera hd_uri video streaming
          mode:
            type: string
            description: Camera state
            enum:
              - on
              - off
              - schedule
          algo:
            type: string
            description: Detection algorithm
          location:
            type: object
            properties:
              lng:
                type: number
                description: Location of longitude
              lat:
                type: number
                description: Location of latitude
          detect_params:
            type: object
            properties:
              threshold:
                type: number
                description: Camera detection parameter
          rules:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: Detection rule name
                mode:
                  type: string
                  description: Camera detects the rule state
                start_at:
                  type: integer
                  description: Algorithm detects the start time
                  format: int32
                end_at:
                  type: integer
                  description: Algorithm detects the end time
                  format: int32
                algo:
                  type: string
                  description: Detection algorithm
                region:
                  type: string
                  description: Detection range

    CameraListResult:
      description: View all camera information
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/CameraInfo'

    CameraInfo:
      type: object
      properties:
        id:
          type: integer
          description: Camera id
          format: int32
        box_id:
          type: string
          description: Box id
        box:
           $ref: 'boxBoxes.yaml#/components/schemas/BoxInfo'
        name:
          type: string
          description: Camera name
        mac_address:
          type: string
          description: IP address of the camera
        type:
          type: string
          description: Algorithm product type
        notifies:
          type: string
          description: Notify the configuration
          enum:
            - email
            - push
        username:
          type: string
          description: User name of the camera
        password:
          type: string
          description: Camera password
        detect_params:
          type: object
          properties:
            threshold:
              type: number
              description: Camera detection parameter
        mode:
          type: string
          description: Camera state
          enum:
            - on
            - off
            - schedule
        uri:
          type: string
          description: Camera uri video streaming
        hd_uri:
          type: string
          description: Camera hd_uri video streaming
        rules:
          type: array
          items:
            type: object
            properties:
              camera_id:
                type: integer
                description: Camera id
                format: int32
              algo:
                type: object
                properties:
                  name:
                    type: string
                    description: Algo name
                  label:
                    type: string
                    description: Label of the Algo
              id:
                type: integer
                description: Rule id
                format: int32
              mode:
                type: string
                description: Camera detects the rule state
              start_at:
                type: integer
                description: Algorithm detects the start time
              end_at:
                type: integer
                description: Algorithm detects the end time
              algos:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Algo name
                    label:
                      type: string
                      description: Label of the Algo
              region:
                type: string
                description: Detection range
              name:
                type: string
                description: Detection rule name
              params:
                type: object
                properties:
                  param:
                    type: string
                    description: Custom parameter
        upload_video_enabled:
          type: boolean
          description: Upload video or not
          enum:
            - true
            - false
        location:
          type: object
          properties:
            lng:
              type: number
              description: Location of longitude
            lat:
              type: number
              description: Location of latitude
        note:
          type: object
          description: Note info
        should_push:
          type: boolean
          description: Should push events to backend
          enum:
            - true
            - false
        serial_no:
          type: string
          description: Such as room number, asset number, etc.
        state:
          type: string
          description: Camera status
          enum:
            - process
            - ready
            - running
            - offline
        brand:
            type: string
            enum:
              - hikivision
              - fdt
              - dahua
              - axis
              - wansview
        snapshot:
          type: object
          properties:
            content_type:
              type: string
              description: Picture content type
            size:
              type: array
              items:
                type: string
                description: Picture length and width
            file_size:
              type: integer
              description: Image file size
              format: int32
            Key:
              type: string
              description: Store file name
            Bucket:
              type: string
              description: Store path
            url:
              type: string
              description: Snapshot url path
        user_id:
          type: integer
          description: User id
          format: int32
        version:
          type: integer
          description: Camera version
          format: int32
        default_params:
          type: object
          description: Custom parameter

    CreateCameraResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/CameraInfo'

  examples:
    CameraListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 1
              box_id: box_dog_sr_10001
              box:
                id: box_dog_sr_10001
                user_id: 2
                max_camera_cnt: 4
                camera_cnt: 0
                max_detect_cnt: 4
                paid_cnt: 0
                created_at: 2019-09-29T05:36:49Z
                updated_at: 2019-10-06T03:15:15Z
                state:
                  name: online
                  label: Online
                scene: 6
                sequence: 7
                billing:
                  name: paid
                  label: Paid
                upload_video_expire: 1209600
                upload_event_expire: 1209600
                version: 22
                type: pc_v1
                ip_address: 192.168.0.119
                meta:
                  agent:
                    name:
                      name: Box
                      label: Turing Box
                    level: 0
                    version: 0.14.0pre
                    upgradable: true
                    outdated: true
                    upgrading: null
                  max_camera_cnt: 4
                  max_detect_cnt: 4
                cameras:
                  - id: 1
                    name: andyaaaaa
                timezone: UTC
                site: 1
              name: andyaaaaa
              mac_address: 4dbbf8369ebf4a7088e133ee4b3f6461
              type: pc_v1
              notifies: ''
              username: andy
              password: Andy1236
              detect_params:
                threshold: 0.5
              mode: on
              uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
              hd_uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
              rules:
                - camera_id: 1
                  params:
                    a: b124
                  algo:
                    name: person
                    label: Person
                  schedule:
                    type: daily
                    time_slots:
                      - - 1070
                        - 1220
                  params_base: base
                  id: 1
                  mode: on
                  start_at: 0
                  end_at: 0
                  region: ""
                  algos: []
                  name: 人
              upload_video_enabled: false
              location: null
              note:
              should_push: false
              state: offline
              snapshot:
                url: ''
              user_id: 2
              brand:
              version: 12
              default_params: {}

    CreateCameraRequest:
      value:
        box_id: box_dog_sr_10001
        name: andyaaaaa
        mac_address: 4dbbf8369ebf4a7088e133ee4b3f6461
        notifies:
        username: andy
        password: Andy1236
        upload_video_enabled: false
        uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
        hd_uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
        mode: on
        location:
          lng: 0.0
          lat: 0.0
        algo: human
        detect_params:
          threshold: 0.5
        rules:
          - name: rule
            mode: on
            start_at: 0
            end_at: 1
            algo: car,person
            region: 0.151,0.513,0.234,0.135

    CreateCameraResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 1
          box_id: box_dog_sr_10001
          box:
            id: box_dog_sr_10001
            user_id: 2
            max_camera_cnt: 4
            camera_cnt: 0
            max_detect_cnt: 4
            paid_cnt: 0
            created_at: 2019-09-29T05:36:49Z
            updated_at: 2019-10-06T03:15:15Z
            state:
              name: online
              label: Online
            scene: 6
            sequence: 7
            billing:
              name: paid
              label: Paid
            upload_video_expire: 1209600
            upload_event_expire: 1209600
            version: 22
            type: pc_v1
            ip_address: 192.168.0.119
            meta:
              agent:
                name:
                  name: Box
                  label: Turing Box
                level: 0
                version: 0.14.0pre
                upgradable: true
                outdated: true
                upgrading: null
              max_camera_cnt: 4
              max_detect_cnt: 4
            cameras:
              - id: 1
                name: andyaaaaa
            timezone: UTC
            site: 1
          name: andyaaaaa
          mac_address: 4dbbf8369ebf4a7088e133ee4b3f6461
          type: pc_v1
          notifies: ''
          username: andy
          password: Andy1236
          detect_params:
            threshold: 0.5
          mode: on
          uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
          hd_uri: rtsp://192.168.0.1/mpeg4/ch1/sub/av_stream
          rules:
            - camera_id: 1
              params:
                a: b124
              algo: ''
              schedule:
                type: daily
                time_slots:
                  - - 1070
                    - 1220
              params_base: base
              id: 1
              mode: on
              start_at: 0
              end_at: 0
              region: '0.151,0.513,0.234,0.135'
              algos:
                - name: person
                  label: Person
              name: 人
          upload_video_enabled: false
          location:
            lat: 0.0
            lng: 0.0
          note: {}
          should_push: false
          state: offline
          snapshot:
            url: ''
          user_id: 2
          brand:
          version: 12
          default_params: {}
