# Name: test_default.tavern
test_name: Retrieve Route
stages:
  - type: ref
    id: login_customer
  - name: Retrieve Route
    request:
      url: "{url}/route/routes/1"
      method: GET
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
    response:
      status_code: 200
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
