# Name: test_default.tavern
test_name:  Create guard_company
stages:
  - type: ref
    id: login_admin
  - name: Create guard_company
    request:
      url: "{url}/guard_company/guard_companies"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        title: "create_test1"
    response:
      status_code: 201
      body:
        err: !anything
        $ext:
          function: api_tests.utils.validation_method:validate_err_201
