openapi: 3.0.2
components:
  parameters:
    RecordIDParam:
      in: path
      name: id
      required: true
      description: Face track record id
      schema:
        type: integer
        format: int32
    TrackIDParam:
      in: query
      name: tracking_object
      description: Face detection track id
      schema:
        type: string
        format: uuid
    StartAtParam:
      in: query
      name: started_at__gt
      description: Starting time (Is greater than)
      schema:
        type: string
        format: date-time
    StartAtParam2:
      in: query
      name: started_at__lt
      description: Starting time (Less than)
      schema:
        type: string
        format: date-time
    StartAtParam3:
      in: query
      name: started_at__gte
      description: Starting time （Greater than or equal to）
      schema:
        type: string
        format: date-time
    StartAtParam4:
      in: query
      name: started_at__lte
      description: Starting time (Less than or equal to)
      schema:
        type: string
        format: date-time
    EndAtParam:
      in: query
      name: ended_at__gt
      description: Ended time (Is greater than)
      schema:
        type: string
        format: date-time
    EndAtParam2:
      in: query
      name: ended_at__lt
      description: Ended time (Less than)
      schema:
        type: string
        format: date-time
    EndAtParam3:
      in: query
      name: ended_at__gte
      description: Ended time （Greater than or equal to）
      schema:
        type: string
        format: date-time
    EndAtParam4:
      in: query
      name: ended_at__lte
      description: Ended time (Less than or equal to)
      schema:
        type: string
        format: date-time
    CameraIDParam:
      in: query
      name: camera_id
      description: Camera id
      schema:
        type: integer
        format: int32
    SiteIDParam:
      in: query
      name: site_id
      description: Site id
      schema:
        type: integer
        format: int64
    OrgIDParam:
      in: query
      name: organization_id
      description: Organization id
      schema:
        type: integer
        format: int32
    EventIDParam:
      in: query
      name: event_id
      description: Event id
      schema:
        type: integer
        format: int64
    SerialNoParam:
      in: query
      name: serial_no
      description: Tracking object serial no
      schema:
        type: string
    NameParam:
      in: query
      name: name
      description: Tracking object name
      schema:
        type: string
  responses:
    200:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RecordListResult'
          examples:
            response:
              $ref: '#/components/examples/RecordListResult'
    RecordResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RecordResult'
          examples:
            response:
              $ref: '#/components/examples/RecordResult'
  schemas:
    RecordListResult:
      description: Face tracking records list
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/RecordInfo'
    RecordInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Record id
        tracking_object_id:
          type: string
          format: uuid
          description: Tracking id
        created_at:
          type: string
          description: Data create time
          format: date-time
        updated_at:
          type: string
          description: Data update time
          format: date-time
        event_id:
          type: integer
          format: int64
          description: Belongs to the event id
        event_type:
          type: string
          description: Algorithm product type
        started_at:
          type: string
          description: Create time
          format: date-time
        ended_at:
          type: string
          description: End time
        camera_id:
          type: integer
          format: int32
          description: Camera id
        camera_name:
          type: integer
          format: int32
          description: Camera name
        site_id:
          type: integer
          format: int64
          description: Site id
        site_name:
          type: integer
          format: int64
          description: Site name
        organization_id:
          type: integer
          format: int32
          description: Organization id
        img_url:
          type: string
          description: Img path
    RecordResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - $ref: '#/components/schemas/RecordInfo'
  examples:
    RecordListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 1
              tracking_object_id: 4366ea92-b2ee-45aa-8580-2985392518a5
              created_at: '2020-07-11T10:33:45Z'
              updated_at: '2020-07-12T04:57:57Z'
              event_id: 1
              event_type: temperature_abnormal
              started_at: "2019-09-27 06:15:31+00"
              ended_at: "2019-09-27 06:15:31+00"
              camera_id: 1
              camera_name: test_camera
              site_id: 1
              site_name: test_site
              organization_id: 9
              img_url: https://turingvideo-staging-api.s3.amazonaws.com
    RecordResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 1
          tracking_object_id: 4366ea92-b2ee-45aa-8580-2985392518a5
          created_at: '2020-07-11T10:33:45Z'
          updated_at: '2020-07-12T04:57:57Z'
          event_id: 1
          event_type: temperature_abnormal
          started_at: "2019-09-27 06:15:31+00"
          ended_at: "2019-09-27 06:15:31+00"
          camera_id: 1
          camera_name: test_camera
          site_id: 1
          site_name: test_site
          organization_id: 9
          img_url: https://turingvideo-staging-api.s3.amazonaws.com
