openapi: 3.0.2
components:
  parameters:
    RobotIDParam:
      in: query
      name: robot
      description: Robot id
      schema:
        type: string
    SiteIDParam:
      in: query
      name: site
      description: Site id
      schema:
        type: integer
        format: int64
    TargetIDParam:
      in: query
      name: target
      description: Target id
      schema:
        type: integer
        format: int32
    RouteIDParam:
      in: query
      name: route_id
      description: Route id
      schema:
        type: integer
        format: int64
    MapIDParam:
      in: query
      name: map_id
      description: Map id
      schema:
        type: integer
        format: int64
    VisibleParam:
      in: query
      name: target__visible
      description: Visible
      schema:
        type: boolean
        enum:
          - true
          - false
    MediumParam:
      in: query
      name: mediums__name
      description: Medium type
      schema:
        type: string

  responses:
    200:
      description: Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Result'
          examples:
            response:
              $ref: '#/components/examples/Result'
  schemas:
    Result:
      description: Inspection materials 巡检素材
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/InspectionInfo'

    InspectionInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Inspection id
        robot_id:
          type: string
          description: Robot id
        robot:
          type: object
          properties:
            id:
              type: integer
              format: int64
              description: Box camera id
            name:
              type: string
              description: Robot camera name
            type:
              type: string
              description: Algorithm product type
        camera:
          type: object
          properties:
            name:
              type: string
              description: Robot camera name
            lablel:
              type: string
              description: Robot camera name lablel
        started_at:
          type: string
          format: date-time
          description: Create time
        ended_at:
          type: string
          format: date-time
          description: End time
        location:
          type: object
          properties:
            lat:
              type: number
              format: double
              description: Location of latitude
            lng:
              type: number
              format: double
              description: Location of longitude
        mediums:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                description: Medium id
              name:
                type: string
                description: Medium name
              file:
                type: object
                properties:
                  file_size:
                    type: integer
                    format: int32
                    description: Medium file size
                  size:
                    type: array
                    items:
                      type: string
                      description: Medium file length and width
                  content_type:
                    type: string
                    description: File content type
                  url:
                    type: string
                    description: Medium url path
        way_point:
          type: object
          properties:
            x:
              type: number
              format: double
              description: The x axis
            y:
              type: number
              format: double
              description: The y axis
            id:
              type: integer
              format: int64
              description: Way point id
            name:
              type: string
              description: Way point name
            site:
              type: integer
              format: int64
              description: The id of the site that robot belongs to
            map_id:
              type: string
              description: Robot map id
            route_id:
              type: integer
              format: int64
              description: Route id
        type:
          type: string
          enum:
            - scan
            - check
            - manual
          description: Inspection status
        algo_types:
          type: array
          items:
            type: object
            description: Multiple object
            properties:
              name:
                type: string
                description: Algorithms and custom algorithms
              label:
                type: string
                description: Algorithms and custom algorithms names
        target_id:
          type: integer
          format: int32
          description: Inspection point id
        site_id:
          type: integer
          format: int64
          description: Site id
        route_id:
          type: integer
          format: int64
          description: Route id
        map_id:
          type: integer
          format: int64
          description: Map id
        case:
          type: string
        target:
          type: object
          properties:
            id:
              type: integer
              description: Robot inspection point id
            site:
              type: integer
              format: int64
              description: Site id
            serial_no:
              type: string
              description: Serial number, uniqueness of inspection point
            name:
              type: string
              description: Name of inspection point
            floor:
              type: integer
              description: The floor number of the inspection point, `-1` means `B1`, `1` means `F1`
            longitude:
              type: number
              description: The longitude of the inspection point, which is required when using robot to patrol
            latitude:
              type: number
              description: The latitude of the inspection point, which is required when using robot to patrol
            desc:
              type: string
              description: Information description of inspection points
            category:
              type: string
              description: Types of inspection points, such as shops, safe passages, etc.
            latest_inspection_time:
              type: string
              description: The system will automatically update the time of the last patrol


  examples:
    Result:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 184
              robot_id: robot_dog_sr_20002
              robot:
                id: robot_dog_sr_20002
                name: 20002
                type: test_li
              camera:
                name: front
                lablel: Front camera
              started_at: '2019-10-17T07:01:14Z'
              ended_at: '2019-10-17T07:01:14Z'
              location: null
              mediums:
                - id: 185
                  name: snapshot
                  file:
                    size:
                      1920
                      1080
                    content_type: image/jpeg
                    file_size: 528447
                    url: https://wanda-poc.s3.cn-northwest-1.amazonaws.com.cn/users/2/robots/wx
              way_point:
                x: 9.294153850803237
                y: -1.1163073281321914
                id: 23
                name: I Do
                site: 1
                map_id: robot_dog_sr_20002.1570763226327
                route_id: 34
              type: check
              algo_types: []
              target_id: 3
              site_id: null
              route_id: 1
              map_id: 2
              target:
                id: 3
                site: 2
                serial_no: 5-312
                name: 办公室
                floor: 3
                longitude: '116.397128'
                latitude: '39.916527'
                desc: ''
                category: ''
                latest_inspection_time: '2019-08-16T09:15:22Z'
              case: null