openapi: 3.0.2
components:
  requestBodies:
    Request:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Request'
  responses:
    200:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Result'
          examples:
            response:
              $ref: '#/components/examples/Result'
  schemas:
    Request:
      type: object
      properties:
        robots:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Robot id
              version:
                type: integer
                format: int64
                description: Robot version

    Result:
      description: View robot difference
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: object
              properties:
                updates:
                  type: array
                  items:
                    $ref: 'robotRobots.yaml#/components/schemas/RobotInfo'
                deletes:
                  type: array
                  items:
                    type: string

  examples:
    Result:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          updates:
            - id: robot_dog_sr_20002
              tasks:
                -
              detection_config: null
              timezone: Asia/Shanghai
              name: 20002
              notifies: ""
              upload_video_enabled: true
              detect_params:
                algos:
                  - name: person
                    label: Person
                  - name: person:513
                    label: 人群疏散
                threshold: 0.5
                auto_speak_enabled: false
                detect_enabled: true
              patrol_params:
                radius: 4.0
                speed: 0.38
              mac_params:
                detect_macs:
                  -
                detect_macs_enabled: true
                auto_speak_enabled: true
              auto_speak: default
              site: 1
              should_push: true
              user_id: 1
              created_at: '2019-05-24T03:25:27Z'
              updated_at: '2019-10-30T06:44:43Z'
              state:
                status: online
                power_percentage: 47.0
                mode: mapping
              status: offline
              snapshot:
                size:
                  - 1920
                  - 1080
                file_size: 444969
                content_type: image/jpeg
                url: https://data-for-apise1030T06ef9a46db&version=9ca64c37-7da2-4fcd-8a2c-3fc0f3d0bcdc.jpeg
              snapshots:
                front:
                  size:
                    - 1920
                    - 1080
                  file_size: 444969
                  content_type: image/jpeg
                  url: https://data-for-apiserves/5CredeDatest&X-Amz-Signature=1875352-8a2c-3fc0f3d0bcdc.jpeg
              scene: 1188
              sequence: 7
              version: 1603
              cameras:
                - name: front
                  label: Front camera
                - name: rear
                  label: Rear camera
              meta:
                agent:
                  name:
                    name: Robot
                    label: Turing Robox
                  level: 1
                  version: 0.14.3
                  upgradable: null
                  outdated: null
                  upgrading: null
                app_agent:
                  name:
                    name: Bot_Nimbo
                    label: Nimbo App
                  level: 1403
                  version: 0.14.3
                  upgradable: null
                  outdated: null
                  upgrading: null
                mac_types: null
              ip_address: 192.168.0.133
              type: test_li
          deletes:
            -
