openapi: 3.0.2
components:
  responses:
    200:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RobotListResult'
          examples:
            response:
              $ref: '#/components/examples/RobotListResult'
  schemas:
    RobotListResult:
      description: View all robot information
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/RobotInfo'

    RobotInfo:
      type: object
      properties:
        id:
          type: string
          description: Robot id
        tasks:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                description: Task id
              robot_id:
                type: string
                description: Robot id
              route_id:
                type: integer
                format: int64
                description: Route id
              name:
                type: string
                description: Task name
              mode:
                type: string
                enum:
                  - on
                  - off
                  - schedule
                description: Task state
              start_at:
                type: integer
                format: int32
                description: Task start time
              end_at:
                type: integer
                format: int32
                description: Task end time
              route:
                type: object
                properties:
                  version:
                    type: integer
                    description: Route version
                  id:
                    type: integer
                    format: int64
                    description: Route id
                  name:
                    type: string
                    description: Route name
                  points:
                    type: string
                    description: Route points
                  checkpoints:
                    type: string
                    description: Route check points
              created_at:
                type: string
                format: date-time
                description: Data create time
              updated_at:
                type: string
                format: date-time
                description: Data update time
              version:
                type: integer
                format: int64
                description: Route version
              type:
                type: string
                enum:
                  - task
                  - patrol
                description: Route type
        detection_config:
          $ref: '#/components/schemas/DetectionConfig'
        timezone:
          type: string
          description: Robot location time zone
        name:
          type: string
          description: Robot name
        notifies:
          type: string
          description: Notify the configuration
        upload_video_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Upload video or not
        detect_params:
          $ref: '#/components/schemas/DetectParams'
        patrol_params:
          type: object
          description: Patrol parameter configuration
          properties:
            radius:
              type: number
              format: float
              description: Patrol the radius
            speed:
              type: number
              format: float
              description: Patrol speed
        mac_params:
          $ref: '#/components/schemas/MacParams'
        auto_speak:
          type: string
          enum:
            - default
            - ''
          description: |
            The detection status(Corresponding: `Default`/`Disabled`)
        site:
          type: integer
          format: int64
          description: The id of the site that robot belongs to
        should_push:
          type: boolean
          enum:
            - true
            - false
          description: Should push events to backend
        user_id:
          type: integer
          format: int32
          description: User id
        created_at:
          type: string
          format: date-time
          description: Data create time
        updated_at:
          type: string
          format: date-time
          description: Data update time
        state:
          type: object
          properties:
            status:
              type: string
              enum:
                - online
                - offline
                - robot_offline
              description: Robot online status
            power_percentage:
              type: number
              format: float
              description: Robot battery power
            mode:
              type: string
              description: Robot mode
        status:
          type: string
          enum:
            - online
            - offline
            - robot_offline
          description: Robot online status
        snapshot:
          type: object
          properties:
            size:
              type: array
              items:
                type: string
                description: Snapshot file length and width
            content_type:
              type: string
              description: File content type
            file_size:
              type: integer
              format: int32
              description: Snapshot file size
            url:
              type: string
              description: Snapshot url path
        snapshots:
          type: object
          properties:
            front:
              type: object
              properties:
                size:
                  type: array
                  items:
                    type: string
                    description: Snapshot file length and width
                content_type:
                  type: string
                  description: File content type
                file_size:
                  type: integer
                  format: int32
                  description: Snapshot file size
                url:
                  type: string
                  description: Snapshot url path
        scene:
          type: integer
          format: int64
          description: State version
        sequence:
          type: integer
          format: int64
          description: Config version
        version:
          type: integer
          format: int64
          description: Robot version
        cameras:
          type: array
          items:
            type: object
            description: Multiple object
            properties:
              name:
                type: string
                description: Robot camera name
              label:
                type: string
                description: Robot camera name label
        meta:
          type: object
          properties:
            agent:
              type: object
              properties:
                name:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Robot name
                    label:
                      type: string
                      description: Label of the robot
                level:
                  type: integer
                  format: int32
                  description: Robot level
                version:
                  type: string
                  description: Robot app version
                upgrading:
                  type: string
                  description: Robot app version upgrading
            app_agent:
              type: object
              properties:
                name:
                  type: object
                  properties:
                    name:
                      type: string
                      description: App agent name
                    label:
                      type: string
                      description: App agent name label
                level:
                  type: integer
                  description: App agent level
                version:
                  type: string
                  description: App agent version
                upgrading:
                  type: string
                  description: App agent version upgrading
            mac_types:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    enum:
                      - restricted
                      - favored
                  label:
                    type: string
                    enum:
                      - Restricted
                      - Favored
        type:
          type: string
          description: Algorithm product type
        ip_address:
          type: string
          description: Robot ip address
    DetectionConfig:
      type: object
      properties:
        auto_speak_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Automatic Speak enabled
        detect_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Enable the detection
        detection_rules:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Rule algorithm name
              mode:
                type: string
                description: Rule state
              start_at:
                type: integer
                format: int32
              end_at:
                type: integer
                format: int32
              algos:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Algorithm product name
                    label:
                      type: string
                      description: Algorithm product label
        detection_threshold:
          type: number
          format: float
          description: Camera detection parameter
        meta_id:
          type: integer
          format: int64
          description: Robot meta_id
    MacParams:
      type: object
      properties:
        detect_macs:
          type: array
          items:
            type: object
            properties:
              mac_address:
                type: string
                description: Robot mac address
              name:
                type: string
                description: Robot mac address name
              vendor:
                type: string
                description: Robot mac vendor
              type:
                type: object
                properties:
                  name:
                    type: string
                    enum:
                      - restricted
                      - favored
                  label:
                    type: string
                    enum:
                      - Restricted
                      - Favored
        auto_speak_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Automatic Speak enabled
        detect_macs_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Enable the detection
    DetectParams:
      type: object
      properties:
        algos:
          type: array
          items:
            type: object
            description: Multiple object
            properties:
              name:
                type: string
                description: Algorithm product name
              label:
                type: string
                description: Algorithm product label
        threshold:
          type: number
          format: float
          description: Camera detection parameter
        auto_speak_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Automatic Speak enabled
        detect_enabled:
          type: boolean
          enum:
            - true
            - false
          description: Enable the detection
  examples:
    RobotListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: robot_dog_sr_20002
              tasks:
                -
              detection_config: null
              timezone: Asia/Shanghai
              name: 20002
              notifies: ""
              upload_video_enabled: true
              detect_params:
                algos:
                  - name: person
                    label: Person
                  - name: person:513
                    label: 人群疏散
                threshold: 0.5
                auto_speak_enabled: false
                detect_enabled: true
              patrol_params:
                radius: 4.0
                speed: 0.38
              mac_params:
                detect_macs: []
                detect_macs_enabled: true
                auto_speak_enabled: true
              auto_speak: default
              site: 1
              should_push: true
              user_id: 1
              created_at: '2019-05-24T03:25:27Z'
              updated_at: '2019-10-30T06:44:43Z'
              state:
                status: online
                power_percentage: 47.0
                mode: mapping
              status: offline
              snapshot:
                size:
                  - 1920
                  - 1080
                file_size: 444969
                content_type: image/jpeg
                url: https://data-for-apise1030T06ef9a46db&version=9ca64c37-7da2-4fcd-8a2c-3fc0f3d0bcdc.jpeg
              snapshots:
                front:
                  size:
                    - 1920
                    - 1080
                  file_size: 444969
                  content_type: image/jpeg
                  url: https://data-for-apiserves/5CredeDatest&X-Amz-Signature=1875352-8a2c-3fc0f3d0bcdc.jpeg
              scene: 1188
              sequence: 7
              version: 1603
              cameras:
                - name: front
                  label: Front camera
                - name: rear
                  label: Rear camera
              meta:
                agent:
                  name:
                    name: Robot
                    label: Turing Robox
                  level: 1
                  version: 0.14.3
                  upgrading: null
                app_agent:
                  name:
                    name: Bot_Nimbo
                    label: Nimbo App
                  level: 1403
                  version: 0.14.3
                  upgrading: null
                mac_types: null
              ip_address: 192.168.0.133
              type: test_li

