openapi: 3.0.2
components:
  requestBodies:
    Request:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Request'
          examples:
            request:
              $ref: '#/components/examples/Request'
  responses:
    200:
      description: |
        Content returned after successful request
        * Requires `transcoding`/`decoding` to invoke
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Result'
          examples:
            response:
              $ref: '#/components/examples/Result'
  schemas:
    Request:
      type: object
      required:
        - type
        - challenge
        - ip_addresse
      properties:
        type:
          type: string
          description: Algorithm product type
        challenge:
          type: string
        ip_addresse:
          type: string
    Result:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: object
              description: Content returned by request (JSON type)
              properties:
                id:
                  type: string
                meta:
                  type: object
                  properties:
                    agent:
                      type: object
                      properties:
                        name:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Robot name
                            label:
                              type: string
                              description: Label of the robot
                        level:
                          type: integer
                          format: int32
                          description: Robot level
                        version:
                          type: integer
                          format: int64
                          description: Robot app version
                        upgradable:
                          type: string
                          description: Robot app version upgrade
                        outdated:
                          type: string
                          description: Robot app version expired
                        upgrading:
                          type: string
                          description: Robot app version upgrading
                    app_agent:
                      type: object
                      properties:
                        name:
                          type: object
                          properties:
                            name:
                              type: string
                              description: App agent name
                            label:
                              type: string
                              description: App agent name label
                        level:
                          type: integer
                          format: int32
                          description: App agent level
                        version:
                          type: string
                          description: App agent version
                        upgradable:
                          type: boolean
                          enum:
                            - true
                            - false
                        outdated:
                          type: string
                          description: App agent version expired
                        upgrading:
                          type: string
                          description: App agent version upgrading
                    mac_types:
                      type: string
                ip_address:
                  type: string
                  description: Robot ip address
                type:
                  type: string
                  description: Algorithm product type
                user_id:
                  type: integer
                  format: int32
                  description: User id
                created_at:
                  type: string
                  format: date-time
                  description: Data create time
                updated_at:
                  type: string
                  format: date-time
                  description: Data update time
                state:
                  type: object
                  properties:
                    status:
                      type: string
                      description: Robot online status
                      enum:
                        - online
                        - offline
                        - inactive
                    power_percentage:
                      type: number
                      format: float
                      description: Robot battery power
                    mode:
                      type: string
                      description: Robot mode
                snapshot:
                  type: object
                  properties:
                    size:
                      type: array
                      items:
                        type: string
                        description: Snapshot file length and width
                    content_type:
                      type: string
                      description: File content type
                    file_size:
                      type: integer
                      format: int32
                      description: Snapshot file size
                    url:
                      type: string
                      description: Snapshot url path
                snapshots:
                  type: object
                  properties:
                    front:
                      type: object
                      properties:
                        size:
                          type: array
                          items:
                            type: string
                            description: Snapshot file length and width
                        content_type:
                          type: string
                          description: File content type
                        file_size:
                          type: integer
                          format: int32
                          description: Snapshot file size
                        url:
                          type: string
                          description: Snapshot url path
                scene:
                  type: integer
                  format: int64
                  description: State version
                sequence:
                  type: integer
                  format: int64
                  description: Config version
                version:
                  type: integer
                  format: int64
                  description: Robot version
                cameras:
                  type: array
                  items:
                    type: object
                    description: Multiple object
                    properties:
                      name:
                        type: string
                        description: Robot camera name
                      label:
                        type: string
                        description: Robot camera name label
                timezone:
                  type: string
                  description: Robot location time zone
                name:
                  type: string
                  description: Robot name
                notifies:
                  type: string
                  description: Notify the configuration
                upload_video_enabled:
                  type: boolean
                  enum:
                    - true
                    - false
                  description: Upload video or not
                detect_params:
                  type: object
                  properties:
                    algos:
                      type: array
                      items:
                        type: object
                        description: Multiple object
                        properties:
                          name:
                            type: string
                            description: Algorithm product name
                          label:
                            type: string
                            description: Algorithm product label
                    threshold:
                      type: number
                      format: float
                      description: Camera detection parameter
                    auto_speak_enabled:
                      type: boolean
                      enum:
                        - true
                        - false
                      description: Automatic Speak enabled
                    detect_enabled:
                      type: boolean
                      enum:
                        - true
                        - false
                      description: Enable the detection
                patrol_params:
                  type: object
                  description: Patrol parameter configuration
                  properties:
                    radius:
                      type: number
                      format: float
                      description: Patrol the radius
                    speed:
                      type: number
                      format: float
                      description: Patrol speed
                mac_params:
                  type: object
                  properties:
                    detect_macs:
                      type: array
                      items:
                        type: object
                        properties:
                          mac_address:
                            type: string
                            description: IP address of the robot
                          name:
                            type: string
                            description: Robot name
                          vendor:
                            type: string
                            description: Robot mac vendor
                          type:
                            type: string
                            enum:
                              - restricted
                              - favored
                            description: Robot mac type
                    auto_speak_enabled:
                      type: boolean
                      enum:
                        - true
                        - false
                      description: Automatic Speak enabled
                    detect_macs_enabled:
                      type: boolean
                      enum:
                        - true
                        - false
                      description: Enable the detection
                auto_speak:
                  type: string
                  description: The detection status
                site:
                  type: integer
                  format: int64
                  description: The id of the site that robot belongs to
                should_push:
                  type: boolean
                  enum:
                    - true
                    - false
                  description: Should push events to backend

  examples:
    Request:
      value:
        type: xc_v1
        challenge: "p5jXaQ/CHBaIwnTvPI7h7LVKAWOFL+4OpDqd9WSMgrmHQXi5F+2O+gydCvqM8YXw=="
        ip_address: "192.168.0.1"

    Result:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: robot_dog_sr_20002
          meta:
            agent:
              name:
                name: Robot
                label: Turing Robox
              level: 1
              version: 0.14.3
              upgradable: true
              outdated: null
              upgrading: null
            app_agent:
              name:
                name: Bot_Nimbo
                label: Nimbo App
              level: 1403
              version: 0.14.3
              upgradable: null
              outdated: null
              upgrading: null
            mac_types: null
          ip_address: 192.168.0.133
          type: test_li
          user_id: 1
          created_at: '2019-05-24T03:25:27Z'
          updated_at: '2019-10-30T06:44:43Z'
          state:
            status: online
            power_percentage: 47.0
            mode: mapping
          status: offline
          snapshot:
            size:
              - 1920
              - 1080
            file_size: 444969
            content_type: image/jpeg
            url: https://data-for-apise1030T06ef9a46db&version=9ca64c37-7da2-4fcd-8a2c-3fc0f3d0bcdc.jpeg
          snapshots:
            front:
              size:
                - 1920
                - 1080
              file_size: 444969
              content_type: image/jpeg
              url: https://data-for-apiserves/5CredeDatest&X-Amz-Signature=1875352-8a2c-3fc0f3d0bcdc.jpeg
          scene: 1188
          sequence: 7
          version: 1603
          cameras:
            - name: front
              label: Front camera
            - name: rear
              label: Rear camera
          timezone: Asia/Shanghai
          name: 20002
          notifies: ''
          upload_video_enabled: true
          detect_params:
            algos:
              - name: person
                label: Person
              - name: person:513
                label: 人群疏散
            threshold: 0.5
            auto_speak_enabled: false
            detect_enabled: true
          patrol_params:
              radius: 4.0
              speed: 0.38
          mac_params:
              detect_macs:
                -
              detect_macs_enabled: true
              auto_speak_enabled: true
          auto_speak: default
          site: 1
          should_push: true
