openapi: 3.0.2
components:
  requestBodies:
    Request:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Request'
          examples:
            request:
              $ref: '#/components/examples/Request'
  schemas:
    Request:
      type: object
      properties:
        id:
          type: string
          description: Robot ID
        type:
          type: string
          description: Algorithm product type
        challenge:
          type: string
          description: Robot validation
        ip_address:
          type: string
          description: IP address of the robot



  examples:
    Request:
      value:
        id: robot_dog_sr_20002
        type: xc_v1
        challenge: "p5jXaQ/CHBaIwnTvPI7h7LVKAWOFL+4OpDqd9WSMgrmHQXi5F+2O+gydCvqM8YXw=="
        ip_address: "192.168.0.1"

