openapi: 3.0.2
components:
  parameters:
    RawEventIDParam:
      in: path
      name: pk
      required: true
      description: Raw_event id
      schema:
        type: integer
        format: int32
  responses:
    200:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RawEventResult'
          examples:
            response:
              $ref: '#/components/examples/RawEventResult'
  schemas:
    RawEventResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: 'raw_eventRaw_events.yaml#/components/schemas/RawEvent'

  examples:
    RawEventResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 1
          uuid: b1a49720-6c71-4a18-9af4-c63754ec1938
          camera: 1
          site: 1
          types: intrude:513
          mediums:
            - content_type: image/jpeg
              size:
                = 1280
                - 720
              file_size: 274343
              url: https://dev-data-for-apiserver
            - content_type: text/json
              file_size: 27
              url: https://dev-data-for-apiserver
            - content_type: video/mp4
              file_size: 2743431
              url: https://dev-data-for-apiserver
          started_at: '2020-04-15T07:15:04Z'
          ended_at: '2020-04-15T07:16:04Z'
          mark: unknown
          created_at: '2020-04-15T07:16:04Z'
          updated_at: '2020-04-15T07:16:04Z'

