openapi: 3.0.2
components:
  responses:
    SampleListResult:
      description: |
        Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SampleListResult'
          examples:
            response:
              $ref: '#/components/examples/SampleListResult'

  schemas:
    SampleListResult:
      description: Paged list of sample
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/SampleInfo'
    SampleInfo:
      type: object
      properties:
        started_at:
          type: string
          format: date-time
          description: Sample event start time
        ended_at:
          type: string
          format: date-time
          description: Sample event end time
        data:
          type: string
          format: JSONObjectField
        media:
          type: object
          properties:
            videos:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  file:
                    type: object
                    properties:
                      file_size:
                        type: integer
                        description: Video file size
                        format: int32
                      content_type:
                        type: string
                        description: Choose according to File content type
                        enum:
                          - video/mp4
                          - text/json
                          - image/jpeg
                      url:
                        type: string
                        description: Video url path
        types:
          type: string
          description: Algorithms code
        expiration:
          type: integer
          format: int32
          description: Sample expire date
        created_at:
          type: string
          format: date-time
          description: Sample create time
        updated_at:
          type: string
          format: date-time
          description: Sample update time
        mediums:
          type: array
          description: |
            Mediums contains three 'objects' :
            * {id，name,file{file_size,size,content_type,url},event_id}
            * {id，name,file{file_size,content_type,url},event_id}
            * {id，name,file{file_size,content_type,url},event_id}
          items:
            type: object
            properties:
              id:
                type: integer
                description: Medium id
                format: int32
              name:
                type: string
                description: Medium name
              file:
                type: object
                properties:
                  file_size:
                    type: integer
                    description: Medium file size
                    format: int32
                  size:
                    type: array
                    items:
                      type: string
                      description: Medium file length and width
                  content_type:
                    type: string
                    description: Choose according to File content type
                    enum:
                      - video/mp4
                      - text/json
                      - image/jpeg
                  url:
                    type: string
                    description: Medium url path
              event_id:
                type: integer
                description: Medium belongs to the event id
                format: int32

        status:
          type: string
          description: |
          enum:
            - todo
            - doing
            - done
        mark:
          type: string
          description: Sample mark
          enum:
            - misreport
            - verified
            - unknown
        user:
          type: integer
          description: User id
          format: int32

  examples:
    SampleListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 1
              started_at: '2020-04-15T06:05:00Z'
              ended_at: '2020-04-15T06:05:07Z'
              data: {}
              media:
                videos:
                  - id: 690691
                    name: video
                    file:
                      file_size: 8888
                      content_type: video/mp4
                      url: https://develop-data-turingvideo-com.s3.cn
                    event_id: 229985
                    started_at: '2020-04-05T06:00:57Z'
                    ended_at: '2020-04-05T06:00:57Z'
              types: person
              expiration: 10000
              uuid: e9cc10e1-ddf2-440f-a1ca-cc862a0a0e40
              camera: 1
              site: 1
              created_at: '2020-04-15T06:04:46Z'
              expired_at: '2020-04-16T06:09:00Z'
              mediums:
                -
              status: todo
              mark: misreport
              user: 1
