# Name: test_default.tavern
test_name: Get Global Config
stages:
  - type: ref
    id: login_customer
  - name: Get Agent Meta
    request:
      url: "{url}/web/meta/get_global"
      method: GET
      headers:
        content-type: application/json
        Referer: "{Referer}"
    response:
      status_code: 200
      body:
        ret:
          version: !anyint
        $ext:
          function: api_tests.utils.validation_method:validate_err_200

