# Name: test_default.tavern
test_name: retrieve an target
marks:
  - parametrize:
      key: pk
      vals:
        - 3
        - 4
stages:
  - type: ref
    id: login_customer
  - name: retrieve an target
    request:
      url: "{url}/map/targets/{pk}"
      method: GET
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
    response:
      status_code: 200
      body:
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
        ret:
          id: !int "{pk}"