# Name: test_default.tavern
test_name: Map remove target
stages:
  - type: ref
    id: login_customer
  - name: Map remove target
    request:
      url: "{url}/map/maps/2/remove_target"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        target_id: 4
    response:
      status_code: 200
  - name: Map add target
    request:
      url: "{url}/map/maps/2/add_target"
      method: POST
      headers:
        content-type: application/json
        X-CSRFTOKEN: "{get_csrftoken}"
      json:
        target_id: 4
    response:
      status_code: 200
      body:
        ret:
          id: !anyint
          map_id: 2
          target_id: 4
        $ext:
          function: api_tests.utils.validation_method:validate_err_200
