openapi: 3.0.2
components:
  requestBodies:
    PostRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostRequest'
          examples:
            request:
              $ref: '#/components/examples/PostRequest'
  responses:
    MapListResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MapListResult'
          examples:
            response:
              $ref: '#/components/examples/MapListResult'
    MapResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MapResult'
          examples:
            response:
              $ref: '#/components/examples/MapResult'
  schemas:
    PostRequest:
      type: object
      required:
        - map_config_id
      properties:
        map_config_id:
          type: integer
          format: int32
          description: Map config id
        center_point:
          type: object
          description: |
            Center point of map.
            * Required when map_type of map_config is not image.
          properties:
            lat:
              type: number
              format: double
              description: Location of latitude
            lng:
              type: number
              format: double
              description: Location of longitude
        initial_zoom:
          type: integer
          format: int16
          description: |
            Initial zoom
            * Required when map_type of map_config is not image.
        min_zoom:
          type: integer
          format: int16
          description: |
            Min zoom
            * Required when map_type of map_config is not image.
        max_zoom:
          type: integer
          format: int16
          description: |
            Max zoom
            * Required when map_type of map_config is not image.
        data:
          type: string
          description: (JSON Object Field)
        image:
          type: string
          description: |
            Image (JSON Object Field)
            * Required when map_type of map_config is image.
    MapResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/MapInfo'
    MapListResult:
      description: Map list
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/MapInfo'
    MapInfo:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Map id
        map_config:
          type: object
          properties:
            id:
              type: integer
              format: int32
              description: Map config id
            organization:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                  description: Organization id
                code_name:
                  type: string
                  description: Organization code name
                name:
                  type: string
                  description: Organization name
                owner_id:
                  type: integer
                  format: int32
                  description: Organization owner id
            map_type:
              type: string
              description: Map type(choice)
              enum:
                - image
                - baidu
                - amap
                - tencent
                - feng_map
                - google
                - bing
            config:
              type: string
              description: Config(JSON Object Field)
            is_default:
              type: boolean
              enum:
                - true
                - false
        targets:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: Map targets id
              target_type:
                type: string
                description: Target type
                enum:
                  - point
                  - polygons
                  - auto
                  - position
              point:
                type: object
                description: Latitude and longitude
                properties:
                  lat:
                    type: number
                    format: double
                    description: Location of latitude
                  lng:
                    type: number
                    format: double
                    description: Location of longitude
              polygons:
                type: array
                items:
                  type: string
                  description: Required when target_type is point or auto.
              position:
                type: object
                properties:
                  x:
                    type: number
                    format: double
                    description: The x axis
                  y:
                    type: number
                    format: double
                    description: The y axis
                  z:
                    type: nubmer
                    format: double
                    description: The z axis
                description: Latitude longitude and floor
              auto_threshold:
                type: integer
                format: float
              name:
                type: string
                description: Target name
              robot_id:
                type: string
              camera_id:
                type: integer
                format: int64
              site_id:
                type: integer
                format: int64
              domain_id:
                type: integer
                format: int32
        center_point:
          type: object
          properties:
            lat:
              type: number
              format: double
              description: Location of latitude
            lng:
              type: number
              format: double
              description: Location of longitude
        initial_zoom:
          type: integer
          format: int16
          description: Initial zoom
        min_zoom:
          type: integer
          format: int16
          description: Min zoom
        max_zoom:
          type: integer
          format: int16
          description: Max zoom
        data:
          type: string
          description: (JSON Object Field)
        image:
          type: object
          properties:
            content_type:
              type: string
              description: Image content type
            file_size:
              type: integer
              format: int32
              description: Image file size
            url:
              type: string
              description: Image url path


  examples:
    PostRequest:
      value:
        map_config_id: 2
        center_point:
          lat: 32.0572355
          lng: 118.77807441
        initial_zoom: 10
        min_zoom: 2
        max_zoom: 8
        data:
          data: test
    MapListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 2
              map_config:
                id: 2
                organization:
                  id: 4
                  code_name: test@163.com
                  name: test@163.com
                  owner_id: 12
                map_type: baidu
                config:
                  test: sugar
                is_default: true
              targets:
                - id: 6
                  target_type: polygons
                  point: null
                  polygons:
                    - points:
                      - lat: 23.21312312312
                        lng: 112.23213213
                      - lat: 24.21312312312
                        lng: 112.43213213
                      - lat: 23.41312312312
                        lng: 112.33213213
                  position: null
                  auto_threshold: 2
                  name: polygons_site
                  robot_id: null
                  camera_id: null
                  site_id: 6
                  domain_id: null
              center_point:
                lat: 32.0572355
                lng: 118.77807441
              initial_zoom: 10
              min_zoom: 2
              max_zoom: 8
              data:
                data: test
              image:
                url: 
              _actions: destroy,update,create

    MapResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 2
          map_config:
            id: 2
            organization:
              id: 4
              code_name: test@163.com
              name: test@163.com
              owner_id: 12
            map_type: baidu
            config:
              test: sugar
            is_default: true
          targets:
            -
          center_point:
            lat: 32.0572355
            lng: 118.77807441
          initial_zoom: 10
          min_zoom: 2
          max_zoom: 8
          data:
            data: test
          image:
            url:
          _actions: destroy,update,create
